name: Run Python Script Daily

on:
  schedule:
    - cron: '20 22 * * *'  # Exécute chaque jour à 22H20 UTC
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Remplace par la version que tu utilises

      - name: Install dependencies
        run: pip install -r requirements.txt  # Mets tes dépendances ici

      - name: Run script
        run: python Weekend_getaway_project.py  # Nom du script
