name: Run Python Script Daily

on:
  schedule:
    - cron: '00 22 * * *'  # Exécute chaque jour à 22H00 UTC
  workflow_dispatch:  # Permet de lancer manuellement si besoin

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set environment variables 
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade pip
          pip install scrapy python-dotenv
      
      - name: Run script
        run: python Weekend_getaway_project.py # Script

      - name: Commit et push des résultats
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global pull.rebase false
          git checkout main
          git pull origin main
          git add final_results.csv
          git commit -m "Auto update of final_results.csv with Actions" || echo "No changes to commit"
          git push origin main

