name: Run Python Script Daily

on:
  schedule:
    - cron: '30 22 * * *'  # Exécute chaque jour à 22H30 UTC
  workflow_dispatch:  # Permet de lancer manuellement si besoin

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: pip install -r requirements.txt  # Dépendances

      - name: Run script
        run: python Weekend_getaway_project.py # Script principal
